### ISSUE TITLE
Use fprintd integration idea for improvement

### ISSUE THREAD

**Issue by luyatshimbalanga** [boltgolt/howdy#135]
Last month I have a discussion with Fedora Desktop team about howdy, one of them suggested to take a look at [fprintd](https://gitlab.freedesktop.org/libfprint/fprintd) and [fprint](https://fprint.freedesktop.org/) and another pointed that using opencv is less secure. Hope it helps.

**Comment by boltgolt** [comment]
First of all, thanks a lot for bringing Howdy to the attention of the fedora desktop team! I don't agree with both suggestions though.

I like working by the Unix philosophy which states, among other things, ["Do one thing and do it well"](https://en.wikipedia.org/wiki/Unix_philosophy#Do_One_Thing_and_Do_It_Well). Howdy is not a general authentication tool and adding fingerprint reader support would divert it from it's primary mission: IR face authentication. Most Windows Hello IR enabled laptops don't even come with a fingerprint reader. I'd suggest taking a look at [FIngerprint-GUI](http://www.ullrich-online.cc/fingerprint/) which does one thing and did it very well on my last laptop that _did_ have a fingerprint reader.

As for security: I've always stated that Howdy is a more convenient way of authenticating, not a more secure one. The readme has included a note since [v1](https://github.com/boltgolt/howdy/tree/1d4308cc0aab95b1299a6fa5d87d3e4ed372e178#a-note-on-security) explaining this. I do my best to make everything as secure as possible, but i always have to maintain a balance between security and ease of use.

Even though i don't agree with them, i do really appreciate the feedback and will update the readme to be even more clear about the security standpoint.
