### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by wrtechnopath** [boltgolt/howdy#332]
Tried installing and got this error, installed pam python using `pip install python-pam`, rebooted and still the same error.

> I'm using openSUSE` Tumbleweed 20200409

> Error and image to follow:

[conflicts.txt](https://github.com/boltgolt/howdy/files/4466300/conflicts.txt)
![Howdy conflicts](https://user-images.githubusercontent.com/14607075/79068873-02546e80-7c7f-11ea-947b-5a1f6d7293f8.png)

**Comment by boltgolt** [comment]
Could you try `pip3 install python-pam`?

**Comment by pguinet** [comment]
Installed wheel and python-pam but still the same error (nothing provides pam-python).
Changed alternatives in order to have Python 3 as default.

NAME="openSUSE Tumbleweed"
# VERSION="20200502"

# python --version
Python 3.8.2

# pip3 install python-pam
Requirement already satisfied: python-pam in /usr/local/lib/python3.8/site-packages (1.8.4)

I even copied pam.py and python_pam-1.8.4.dist-info/ to /usr/lib/python3.8/site-packages
