### ISSUE TITLE
AttributeError: 'VideoCapture' object has no attribute 'internal'

### ISSUE THREAD

**Issue by leoheck** [boltgolt/howdy#498]
I am running this for the first time, not sure if I am doing this right.
I am seeing this issue

![image](https://user-images.githubusercontent.com/1277920/104972746-6ad03900-59d1-11eb-820d-ab3c2aeaed6e.png)

I am not sure which version I am using.  There is no way to get this info from the command line.
However, I am using ubuntu's PPA.
![image](https://user-images.githubusercontent.com/1277920/104972811-9ce19b00-59d1-11eb-91d0-c55bec1657a7.png)

**Comment by leoheck** [comment]
It looks like the config file was not filled with the default values.
The device_path was not right. 
What if you use the /dev/video0 as default instead of something that does not mean anything by default?

**Comment by leoheck** [comment]
Found a way to get the version, but please, consider using the standard way for these things with (-v --version)
![image](https://user-images.githubusercontent.com/1277920/104973835-d1a32180-59d4-11eb-92cc-188194a86d6c.png)


Also, why it has to open the camera to tell the version and then exit?

**Comment by boltgolt** [comment]
The standard template for making an issue on GitHub literally tells you to run `sudo howdy version`, but you skipped using the bug template. It's also in the documentation and help text. 

If you actually read the error it says that the camera is configured incorrectly and to edit the device_path config option. 

`/dev/video0` is not a specific camera, it can change camera device on reboot because it's assigned by V4L. This would lead to a lot of big reports about randomly switching cameras. Use a by-path camera to keep using the same device 

It's opening the camera because you run it with sudo and howdy is enabled on your system. 

Please think before you post

**Comment by barbalex** [comment]
I am having the exact same problem.

Unfortunately the solution does not seem very clear to me.

How exactly can this problem be solved?

**Comment by leoheck** [comment]
Oh, couldn't quite grasp it, so naturally, I just hit the delete button on my computer. Because, you know, typing a password like a regular human is just a breezeway easier and totally not a hassle at all.

**Comment by barbalex** [comment]
I now found the solution here: https://github.com/boltgolt/howdy/issues/460#issuecomment-719905912
It seems that the device path is not set in Pop OS and has to be set via `sudo howdy config`
