### ISSUE TITLE
BadAccess, BadShmSeg

### ISSUE THREAD

**Issue by duart38** [boltgolt/howdy#60]
_Please describe the issue in as much detail as possible, including any errors and traces_

I get this when i run the test command

X Error: BadAccess (attempt to access private resource denied) 10
  Extension:    130 (MIT-SHM)
  Minor opcode: 1 (X_ShmAttach)
  Resource id:  0x2e00003
X Error: BadShmSeg (invalid shared segment parameter) 128
  Extension:    130 (MIT-SHM)
  Minor opcode: 5 (X_ShmCreatePixmap)
  Resource id:  0x2e0000d

----

**Linux distribution (if applicable)**: Ubuntu 18.04.1
**Howdy version**:

**Comment by boltgolt** [comment]
Could you try running `QT_X11_NO_MITSHM=1`, and then trying the test command again?

**Comment by keckes** [comment]
Hi there, thanks for putting this together!

I had the same issue upon trying to run `sudo howdy test` and the viewer window was blank.

I tried running `sudo QT_X11_NO_MITSHM=1 howdy test` and it worked, though the image it returned was basically blank (see attached) and not dynamic (the image didn't really change even as I moved my face closer to the camera/emitters or waved my hand in front of them).

When I try using howdy normally it just times out and I have to enter the password. I assume it's because the image is not actually dynamic (i.e. not even recognizing something that resembles a face).

I'm running Ubuntu 18.04 LTS on a Thinkpad T480s.
![howdy-test](https://user-images.githubusercontent.com/42268235/43951671-fce0be76-9c93-11e8-84b9-f202281235a0.png)

**Comment by boltgolt** [comment]
This is a known decoding error in some cameras, could you try running `sudo howdy config` and setting `force_mjpeg` to true?

**Comment by keckes** [comment]
OK, did that and the test procedure gives an actual image -- great! 

I just added two versions of my face (with and without glasses) to my profile then tried a few tests. Unfortunately I still get the timeout problem, so I still have to enter my password manually.

**Comment by boltgolt** [comment]
Try upping the `certainty` value, howdy might be recognizing you with too little match certainty.

**Comment by keckes** [comment]
I upped the `certainty` value to 9 and lowered the `dark_threshold` to 1 but still got the timeout error. 

I noticed that when I run the test procedure, the frame rate and exposure consistency seems to depend heavily on the distance between my face and the emitters/camera. Still, even when I added a new face based on the distance and position I felt was most consistent in the test procedure, I still get the timeout errors.

Any other suggestions?

**Comment by boltgolt** [comment]
Following up on issues i forgot to reply to, are you still having this problem or did you fix it/uninstall Howdy?

**Comment by keckes** [comment]
Hi, thanks for checking in. I disabled (but didn't uninstall) Howdy because
I could never get it to recognize me, no matter how much I tweaked the
parameters. I had written earlier about how the output was just greenish
static when I used the "sudo howdy test" command, so perhaps the
authentication routine is getting the same data every time it turns on the
camera and of course it in no way resembles a face.

**Comment by boltgolt** [comment]
Greenish static is a new symptom for me, does this static also show up when you open Cheese (search for Cheese in the dash)? You might need to try out different webcams/video sizes in the Preferences menu.

**Comment by keckes** [comment]
Indeed it does show up initially in Cheese because the default camera is
the one associated with the IR emitters. I always have to select the normal
webcam in the Preferences menu to get a clear picture.

**Comment by boltgolt** [comment]
So Cheese is also just getting the garbage data? Does switching resolutions in the preferences change anything?

**Comment by keckes** [comment]
Yep, the cheese default is the IR camera at 480x400 and it's the green
garbage. Upon switching resolutions to 400x400 it looks as expected,
however.

**Comment by boltgolt** [comment]
Great! Could you set the frame size in `sudo howdy config` to that format:

```
frame_width = 400
frame_height = 400
```

This should fix the problem.

**Comment by nilmerg** [comment]
Had the same problem, running it with `sudo QT_X11_NO_MITSHM=1 howdy test` finally worked.

**Comment by mbprado** [comment]
I had exactly the same issue. 
I was able so see my image in test, but it never had been recognized. Also, is test, using IR camera, i never shown the red circle around my face (testing with the normal camera, everything worked fine). I completely solved the issue with the steps bellow:

1 - To fix green image:
In howdy config, simply set ( no need to set force_mjpeg or anything else):
`frame_width = 400 `
`frame_height = 400`

2 - To fix testing interface: 
add the line to /etc/environment
`QT_X11_NO_MITSHM=1`

3 - Finally to get the correct detection, including the red circle in howdy test, I had to set bright and contrast  the parameters in v4l:

`v4l2-ctl -d /dev/video0 --set-ctrl=contrast=0`
and: 
`v4l2-ctl -d /dev/video0 --set-ctrl=brightness=255`
check with: 



 `$ v4l2-ctl -d /dev/video0 --list-ctrls`
 `                    brightness 0x00980900 (int)    : min=0 max=255 step=1 default=128 value=255`
`                       contrast 0x00980901 (int)    : min=0 max=255 step=1 default=32 value=0`

Doing this, I had no more problem with detection with IR camera.
